#!/usr/bin/env bash
desc="Kubernetes quick multi-utils cluster access utility"
ver="20180805"

# written by Ugo Viti <ugo.viti@initzero.it>

# INSTALL:
# prerequisites: yum install multitail rxvt dvtm kubectl google-cloud-sdk
# copy this script into ~/bin/kutil and run:
# cd ~/bin && chmod 755 kutil && for file in klog ktop kbash ktail kdesc ; do ln -s kutil $file; done

kubeutil=$(basename $0)

kubecmd() {
 local pod=$1
 case $kubeutil in
	 kbash) [ -z "$opts" ] && opts="/bin/sh" ; echo "kubectl $args exec -it $pod $([ ! -z "$container" ] && echo "-c $container") -- $opts" ;;
	 kdesc) echo "kubectl $args describe pod $pod $follow $opts | less" ;;
	 klog)  [ -z "$podnumber" ] && follow="-f" ;  echo "kubectl $args logs $pod $container $follow $opts" ;;
	 ktail) echo "kubectl $args exec -it $pod $([ ! -z "$container" ] && echo "-c $container") -- tail -f $opts" ;;
	 ktop)  [ -z "$podnumber" ] && opts+="" ; echo "kubectl $args exec -it $pod $([ ! -z "$container" ] && echo "-c $container") -- top $opts" ;;
	 #ktop)  [ -z "$podnumber" ] && opts+="-bn 1" ; echo "kubectl $args exec -it $pod -c $container -- top $opts" ;; # top args test
 esac
}

kubemulti() {
 if [[ -z "$podnumber" && ${#pods[@]} -gt 1 ]]; then
  kubecmd+="\"$(kubecmd ${pods[0]})\""

  for pod in ${pods[@]:1}; do
	# test: list containers in a pod
	# kubectl -n test get pods $pod -o jsonpath='{.spec.containers[*].name}' | cut -d " " -f 1

	case $kubeutil in
		#ktop)  kubecmd+=" \; split-window \"$(kubecmd $pod)\"" ;; # tmux test
		kbash|ktop) kubecmd+=" \"$(kubecmd $pod)\"" ;;
		#kdesc)  kubecmd+=" -r 120 -l \"$(kubecmd $pod)\"" ;;
		kdesc)  kubecmd+=" \"$(kubecmd $pod)\"" ;;
		klog|ktail)  kubecmd+=" -l \"$(kubecmd $pod)\"" ;;
	esac
  done
  else
   kubecmd="$(kubecmd ${pods[$podnumber]})"
 fi
 echo "$kubecmd"
}

pods_get() {
	#pods=( $(kubectl get pods | grep ^${pod} | grep -e Running -e ContainerCreating | cut -f 1 -d ' ') )
	pods=( $(kubectl get pods $args | grep -v ^NAME | grep ^${pod} | grep -v "Evicted" | cut -f 1 -d ' ') )
}

print_pod_not_founds() {
	echo -e "No PODs founds $([ -n "$pod" ] && echo "named: $pod") $([ -n "$namespace" ] && echo "in current namespace: $namespace") \nexiting now..." && exit 1
}

main() {
[ -n $pods ] && pods_get || echo "No POD specified... exiting now"
# simultaneous multiple pods management
if   [[ ${#pods[@]} -eq 0 ]]; then
	print_pod_not_founds
elif [[ -z "$podnumber" && ${#pods[@]} -gt 1 ]]; then
	case $kubeutil in
		kbash)
			#echo "specify the pod number you want to connect (total active $container pods: ${#pods[@]})"
			#exit 1
			eval "dvtm $(kubemulti)"
			;;
		kdesc)
			#eval "multitail -s 2 -r 120 -l $(kubemulti)"
			eval "dvtm $(kubemulti)"
			;;
		ktop)
			#eval "tmux new-session -d $(kubemulti) \; attach"
			eval "dvtm $(kubemulti)"
			;;
		klog)
			eval "multitail -s 2 -l $(kubemulti)"
			;;
		ktail)
			[ -z "$opts" ] && echo "ERROR: specify remote log file to tail" && exit 1
			eval "multitail -s 2 -l $(kubemulti)"
			;;

		kusage)
			kusage
			;;
	esac	
else
	if [[ $podnumber -gt ${#pods[@]} ]]; then
		echo "invalid pod number specified: $podnumber (total active $container pods: ${#pods[@]})"
	else
		let podnumber-=1
		pod=${pods[$podnumber]}
		eval "$(kubemulti)"
	fi
fi
}

kusage() {
	set -e
	local node_count=0
	local total_percent_cpu=0
	local total_percent_mem=0
	local readonly nodes=$(kubectl get nodes --no-headers -o custom-columns=NAME:.metadata.name)

	for n in $nodes; do
		local requests=$(kubectl describe node $n | grep -A2 -E "^\\s*CPU Requests" | tail -n1)
		local percent_cpu=$(echo $requests | awk -F "[()%]" '{print $2}')
		local percent_mem=$(echo $requests | awk -F "[()%]" '{print $8}')
		echo "$n: ${percent_cpu}% CPU, ${percent_mem}% memory"

		node_count=$((node_count + 1))
		total_percent_cpu=$((total_percent_cpu + percent_cpu))
		total_percent_mem=$((total_percent_mem + percent_mem))
	done

	local readonly avg_percent_cpu=$((total_percent_cpu / node_count))
	local readonly avg_percent_mem=$((total_percent_mem / node_count))

	echo "Average usage: ${avg_percent_cpu}% CPU, ${avg_percent_mem}% memory."

}

###################################################################
#################### default program menu and arguments validations
# command prompt menu
usage(){
  echo "$kubeutil - $desc
Written by Ugo Viti <ugo.viti@initzero.it>
version: $ver

usage: $kubeutil [options]

Option:  Argument:           Description:
--------------------------------------------------------------------------------

Input/Output file management:
  -p     <pod name>          the POD name
  -c     <container name>    the container name (if empty, show the first container)
  -r     <pod number>        if the pod is scaled to >1 replica, show the corresponding pod number) 
  -n     <namespace>         namespace
  -f                         continuos logs watch
  -l                         list all pods
  -h                         show this help
"
}


NO_ARGS=0
E_OPTERROR=65

# if not command args, then connect to the cluster nodes
if [ $# -eq "$NO_ARGS" ]  # Script invoked with no command-line args?
 then
  case $(basename $0) in
	  kbash) eval DVTM_TERM=rxvt dvtm $(kubectl get nodes | grep -v ^NAME | cut -d " " -f 1 | while read node ; do echo -n "\"gcloud compute ssh $node\" "; done) && exit 0 ;;
	  ktop) eval DVTM_TERM=rxvt dvtm $(kubectl get nodes | grep -v ^NAME | cut -d " " -f 1 | while read node ; do echo -n "\"gcloud compute ssh $node -- top\" "; done) && exit 0 ;;
	  klog) eval DVTM_TERM=rxvt dvtm $(kubectl get nodes | grep -v ^NAME | cut -d " " -f 1 | while read node ; do echo -n "\"gcloud compute ssh $node -- sudo journalctl -f -u kubelet | grep -v -e \"/stats/summary/:\" -e \"/healthz:\" -e \"Discovered runtime cgroups name:\"\" "; done) && exit 0 ;;
	  kusage) kusage && exit 0;;
  esac
  echo $0
  usage
  exit $E_OPTERROR        # Exit and explain usage, if no argument(s) given.
fi

# Usage: scriptname -options
# Note: dash (-) necessary

while getopts "lp:c:r:n:flh" option ; do
  case $option in
    p) # pods group name
        pod="${OPTARG}"
        ;;
    c) # container name
        container="$OPTARG"
        ;;
    r) # pod number
        replica="$OPTARG"
        ;;
    n) # namespace
        namespace="$OPTARG"
        args+="-n $namespace"
        ;;
    f) # continuous watch like tail -f
        opts+=" -f"
        ;;
    l) # list all pods
	action="list"
        ;;
    h) # display this help menu
        usage
        exit 0
        ;;
    *)
        usage
        echo "invalid switch specified - abort." >&2
        exit 1
        ;;
  esac
done
# Move argument pointer to next.
shift $(($OPTIND - 1))


#[ -z "$pod" ] && usage && echo "please specify a pod name" && exit 1
#[ -z "$namespace" ] && namespace="default"
[ -z "$pod" ] && pod="$1" && shift
[ -z "$container" ] && container="$1" && shift

opts+="$@"

if [ "$action" = "list" ]; then
        pods_get
	if [[ ${#pods[@]} -eq 0 ]]; then
		print_pod_not_founds
	else
		i=1 ; for pod in ${pods[@]}; do echo "$i: $pod" ; let i+=1; done
	fi
	exit 0
fi

main
